export { fill, fills } from './Fill'
export { drawText } from './FillText'
export { stroke, strokes } from './Stroke'
export { strokeText, strokesText, drawTextStroke } from './StrokeText'
export { shape } from './Shape'
export { computeFill, computeStroke } from './Compute'