export { fill, fills } from './Fill'
export { fillText } from './FillText'
export { stroke, strokes } from './Stroke'
export { strokeText, drawTextStroke } from './StrokeText'
export { shape } from './Shape'
export { compute } from './Compute'
export { recycleImage } from './paint/image'
